// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  InlineResponse20039,
  InlineResponse20039FromJSON,
  InlineResponse20039ToJSON,
} from '../models'

/**
 *
 */
export class IBCustApi extends runtime.BaseAPI {
  /**
   * Returns Applicant Id with all owner related entities
   * IBCust Entity Info
   */
  async ibcustEntityInfoGetRaw(
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<Array<InlineResponse20039>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/ibcust/entity/info`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(InlineResponse20039FromJSON)
    )
  }

  /**
   * Returns Applicant Id with all owner related entities
   * IBCust Entity Info
   */
  async ibcustEntityInfoGet(
    initOverrides?: RequestInit
  ): Promise<Array<InlineResponse20039>> {
    const response = await this.ibcustEntityInfoGetRaw(initOverrides)
    return await response.value()
  }
}
