// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  InlineResponse20031,
  InlineResponse20031FromJSON,
  InlineResponse20031ToJSON,
} from "../models";

/**
 *
 */
export class PnLApi extends runtime.BaseAPI {
  /**
   * Returns an object containing PnL for the selected account and its models (if any). To receive streaming PnL the endpoint /ws can be used. Refer to [Streaming WebSocket Data](https://interactivebrokers.github.io/cpwebapi/RealtimeSubscription.html) for details.
   * PnL for the selected account
   */
  async iserverAccountPnlPartitionedGetRaw(
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<InlineResponse20031>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/iserver/account/pnl/partitioned`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      InlineResponse20031FromJSON(jsonValue)
    );
  }

  /**
   * Returns an object containing PnL for the selected account and its models (if any). To receive streaming PnL the endpoint /ws can be used. Refer to [Streaming WebSocket Data](https://interactivebrokers.github.io/cpwebapi/RealtimeSubscription.html) for details.
   * PnL for the selected account
   */
  async iserverAccountPnlPartitionedGet(
    initOverrides?: RequestInit
  ): Promise<InlineResponse20031> {
    const response = await this.iserverAccountPnlPartitionedGetRaw(
      initOverrides
    );
    return await response.value();
  }
}
