// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { Trade, TradeFromJSON, TradeToJSON } from "../models";

/**
 *
 */
export class TradesApi extends runtime.BaseAPI {
  /**
   * Returns a list of trades for the currently selected account for current day and six previous days. It is advised to call this endpoint once per session.
   * List of Trades for the selected account
   */
  async iserverAccountTradesGetRaw(
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<Array<Trade>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/iserver/account/trades`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TradeFromJSON)
    );
  }

  /**
   * Returns a list of trades for the currently selected account for current day and six previous days. It is advised to call this endpoint once per session.
   * List of Trades for the selected account
   */
  async iserverAccountTradesGet(
    initOverrides?: RequestInit
  ): Promise<Array<Trade>> {
    const response = await this.iserverAccountTradesGetRaw(initOverrides);
    return await response.value();
  }
}
