// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CalendarRequestFilters
 */
export interface CalendarRequestFilters {
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  recentlyHeld?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  corporateEarnings?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  divExDates?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  ipo?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  splits?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  corporateEvents?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  economicEvents?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  optionShowMonthly?: string;
  /**
   * value can be 'true' or 'false'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  optionShowWeekly?: string;
  /**
   * default is 'All'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  country?: string;
  /**
   * default is '250'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  limit?: string;
  /**
   * default is '50'.
   * @type {string}
   * @memberof CalendarRequestFilters
   */
  limitRegion?: string;
}

export function CalendarRequestFiltersFromJSON(
  json: any
): CalendarRequestFilters {
  return CalendarRequestFiltersFromJSONTyped(json, false);
}

export function CalendarRequestFiltersFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CalendarRequestFilters {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    recentlyHeld: !exists(json, "recently_held")
      ? undefined
      : json["recently_held"],
    corporateEarnings: !exists(json, "corporate_earnings")
      ? undefined
      : json["corporate_earnings"],
    divExDates: !exists(json, "DivExDates") ? undefined : json["DivExDates"],
    ipo: !exists(json, "ipo") ? undefined : json["ipo"],
    splits: !exists(json, "splits") ? undefined : json["splits"],
    corporateEvents: !exists(json, "corporate_events")
      ? undefined
      : json["corporate_events"],
    economicEvents: !exists(json, "economic_events")
      ? undefined
      : json["economic_events"],
    optionShowMonthly: !exists(json, "option_show_monthly")
      ? undefined
      : json["option_show_monthly"],
    optionShowWeekly: !exists(json, "option_show_weekly")
      ? undefined
      : json["option_show_weekly"],
    country: !exists(json, "country") ? undefined : json["country"],
    limit: !exists(json, "limit") ? undefined : json["limit"],
    limitRegion: !exists(json, "limit_region")
      ? undefined
      : json["limit_region"],
  };
}

export function CalendarRequestFiltersToJSON(
  value?: CalendarRequestFilters | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    recently_held: value.recentlyHeld,
    corporate_earnings: value.corporateEarnings,
    DivExDates: value.divExDates,
    ipo: value.ipo,
    splits: value.splits,
    corporate_events: value.corporateEvents,
    economic_events: value.economicEvents,
    option_show_monthly: value.optionShowMonthly,
    option_show_weekly: value.optionShowWeekly,
    country: value.country,
    limit: value.limit,
    limit_region: value.limitRegion,
  };
}
