// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CalendarRequestDate,
  CalendarRequestDateFromJSON,
  CalendarRequestDateFromJSONTyped,
  CalendarRequestDateToJSON,
  CalendarRequestFilters,
  CalendarRequestFiltersFromJSON,
  CalendarRequestFiltersFromJSONTyped,
  CalendarRequestFiltersToJSON,
} from './'

/**
 *
 * @export
 * @interface CalendarRequest
 */
export interface CalendarRequest {
  /**
   *
   * @type {CalendarRequestDate}
   * @memberof CalendarRequest
   */
  date?: CalendarRequestDate
  /**
   *
   * @type {CalendarRequestFilters}
   * @memberof CalendarRequest
   */
  filters?: CalendarRequestFilters
}

export function CalendarRequestFromJSON(json: any): CalendarRequest {
  return CalendarRequestFromJSONTyped(json, false)
}

export function CalendarRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CalendarRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    date: !exists(json, 'date')
      ? undefined
      : CalendarRequestDateFromJSON(json['date']),
    filters: !exists(json, 'filters')
      ? undefined
      : CalendarRequestFiltersFromJSON(json['filters']),
  }
}

export function CalendarRequestToJSON(value?: CalendarRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    date: CalendarRequestDateToJSON(value.date),
    filters: CalendarRequestFiltersToJSON(value.filters),
  }
}
