/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ContractRules
 */
export interface ContractRules {
  /**
   *
   * @type {Array<string>}
   * @memberof ContractRules
   */
  orderTypes?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ContractRules
   */
  orderTypesOutside?: Array<string>;
  /**
   * default quantity you can use to place an order
   * @type {number}
   * @memberof ContractRules
   */
  defaultSize?: number;
  /**
   *
   * @type {number}
   * @memberof ContractRules
   */
  sizeIncrement?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ContractRules
   */
  tifTypes?: Array<string>;
  /**
   * default limit price you can use to prefill your order
   * @type {number}
   * @memberof ContractRules
   */
  limitPrice?: number;
  /**
   * default stop price you can use to prefill your order
   * @type {number}
   * @memberof ContractRules
   */
  stopprice?: number;
  /**
   * if you can preview the order or not with the whatif endpoint
   * @type {boolean}
   * @memberof ContractRules
   */
  preview?: boolean;
  /**
   *
   * @type {string}
   * @memberof ContractRules
   */
  displaySize?: string;
  /**
   *
   * @type {string}
   * @memberof ContractRules
   */
  increment?: string;
}

export function ContractRulesFromJSON(json: any): ContractRules {
  return ContractRulesFromJSONTyped(json, false);
}

export function ContractRulesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ContractRules {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderTypes: !exists(json, "orderTypes") ? undefined : json["orderTypes"],
    orderTypesOutside: !exists(json, "orderTypesOutside")
      ? undefined
      : json["orderTypesOutside"],
    defaultSize: !exists(json, "defaultSize") ? undefined : json["defaultSize"],
    sizeIncrement: !exists(json, "sizeIncrement")
      ? undefined
      : json["sizeIncrement"],
    tifTypes: !exists(json, "tifTypes") ? undefined : json["tifTypes"],
    limitPrice: !exists(json, "limitPrice") ? undefined : json["limitPrice"],
    stopprice: !exists(json, "stopprice") ? undefined : json["stopprice"],
    preview: !exists(json, "preview") ? undefined : json["preview"],
    displaySize: !exists(json, "displaySize") ? undefined : json["displaySize"],
    increment: !exists(json, "increment") ? undefined : json["increment"],
  };
}

export function ContractRulesToJSON(value?: ContractRules | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orderTypes: value.orderTypes,
    orderTypesOutside: value.orderTypesOutside,
    defaultSize: value.defaultSize,
    sizeIncrement: value.sizeIncrement,
    tifTypes: value.tifTypes,
    limitPrice: value.limitPrice,
    stopprice: value.stopprice,
    preview: value.preview,
    displaySize: value.displaySize,
    increment: value.increment,
  };
}
