/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  HistoryResultBars,
  HistoryResultBarsFromJSON,
  HistoryResultBarsFromJSONTyped,
  HistoryResultBarsToJSON,
} from "./";

/**
 *
 * @export
 * @interface HistoryResult
 */
export interface HistoryResult {
  /**
   *
   * @type {HistoryResultBars}
   * @memberof HistoryResult
   */
  bars?: HistoryResultBars;
}

export function HistoryResultFromJSON(json: any): HistoryResult {
  return HistoryResultFromJSONTyped(json, false);
}

export function HistoryResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HistoryResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    bars: !exists(json, "bars")
      ? undefined
      : HistoryResultBarsFromJSON(json["bars"]),
  };
}

export function HistoryResultToJSON(value?: HistoryResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    bars: HistoryResultBarsToJSON(value.bars),
  };
}
