/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IbcustEntityInfoName
 */
export interface IbcustEntityInfoName {
  /**
   *
   * @type {string}
   * @memberof IbcustEntityInfoName
   */
  salutation?: string;
  /**
   *
   * @type {string}
   * @memberof IbcustEntityInfoName
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof IbcustEntityInfoName
   */
  lastName?: string;
}

export function IbcustEntityInfoNameFromJSON(json: any): IbcustEntityInfoName {
  return IbcustEntityInfoNameFromJSONTyped(json, false);
}

export function IbcustEntityInfoNameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IbcustEntityInfoName {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    salutation: !exists(json, "salutation") ? undefined : json["salutation"],
    firstName: !exists(json, "firstName") ? undefined : json["firstName"],
    lastName: !exists(json, "lastName") ? undefined : json["lastName"],
  };
}

export function IbcustEntityInfoNameToJSON(
  value?: IbcustEntityInfoName | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    salutation: value.salutation,
    firstName: value.firstName,
    lastName: value.lastName,
  };
}
