// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  IbcustEntityInfoAddress,
  IbcustEntityInfoAddressFromJSON,
  IbcustEntityInfoAddressFromJSONTyped,
  IbcustEntityInfoAddressToJSON,
  IbcustEntityInfoName,
  IbcustEntityInfoNameFromJSON,
  IbcustEntityInfoNameFromJSONTyped,
  IbcustEntityInfoNameToJSON,
} from "./";

/**
 *
 * @export
 * @interface IbcustEntityInfoEntities
 */
export interface IbcustEntityInfoEntities {
  /**
   *
   * @type {boolean}
   * @memberof IbcustEntityInfoEntities
   */
  canTrade?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof IbcustEntityInfoEntities
   */
  canSign?: boolean;
  /**
   *
   * @type {string}
   * @memberof IbcustEntityInfoEntities
   */
  type?: string;
  /**
   *
   * @type {IbcustEntityInfoName}
   * @memberof IbcustEntityInfoEntities
   */
  name?: IbcustEntityInfoName;
  /**
   *
   * @type {IbcustEntityInfoAddress}
   * @memberof IbcustEntityInfoEntities
   */
  address?: IbcustEntityInfoAddress;
  /**
   *
   * @type {Array<object>}
   * @memberof IbcustEntityInfoEntities
   */
  identDocs?: Array<object>;
}

export function IbcustEntityInfoEntitiesFromJSON(
  json: any
): IbcustEntityInfoEntities {
  return IbcustEntityInfoEntitiesFromJSONTyped(json, false);
}

export function IbcustEntityInfoEntitiesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IbcustEntityInfoEntities {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    canTrade: !exists(json, "canTrade") ? undefined : json["canTrade"],
    canSign: !exists(json, "canSign") ? undefined : json["canSign"],
    type: !exists(json, "type") ? undefined : json["type"],
    name: !exists(json, "name")
      ? undefined
      : IbcustEntityInfoNameFromJSON(json["name"]),
    address: !exists(json, "address")
      ? undefined
      : IbcustEntityInfoAddressFromJSON(json["address"]),
    identDocs: !exists(json, "identDocs") ? undefined : json["identDocs"],
  };
}

export function IbcustEntityInfoEntitiesToJSON(
  value?: IbcustEntityInfoEntities | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    canTrade: value.canTrade,
    canSign: value.canSign,
    type: value.type,
    name: IbcustEntityInfoNameToJSON(value.name),
    address: IbcustEntityInfoAddressToJSON(value.address),
    identDocs: value.identDocs,
  };
}
