/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { Ledger, LedgerFromJSON, LedgerFromJSONTyped, LedgerToJSON } from "./";

/**
 *
 * @export
 * @interface InlineResponse20036
 */
export interface InlineResponse20036 {
  /**
   *
   * @type {Ledger}
   * @memberof InlineResponse20036
   */
  bASE?: Ledger;
}

export function InlineResponse20036FromJSON(json: any): InlineResponse20036 {
  return InlineResponse20036FromJSONTyped(json, false);
}

export function InlineResponse20036FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20036 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    bASE: !exists(json, "BASE") ? undefined : LedgerFromJSON(json["BASE"]),
  };
}

export function InlineResponse20036ToJSON(
  value?: InlineResponse20036 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    BASE: LedgerToJSON(value.bASE),
  };
}
