// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineObject10
 */
export interface InlineObject10 {
  /**
   *
   * @type {Array<string>}
   * @memberof InlineObject10
   */
  acctIds?: Array<string>
}

export function InlineObject10FromJSON(json: any): InlineObject10 {
  return InlineObject10FromJSONTyped(json, false)
}

export function InlineObject10FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject10 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    acctIds: !exists(json, 'acctIds') ? undefined : json['acctIds'],
  }
}

export function InlineObject10ToJSON(value?: InlineObject10 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    acctIds: value.acctIds,
  }
}
