/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  InlineResponse20032Schedules,
  InlineResponse20032SchedulesFromJSON,
  InlineResponse20032SchedulesFromJSONTyped,
  InlineResponse20032SchedulesToJSON,
} from "./";

/**
 *
 * @export
 * @interface InlineResponse20032
 */
export interface InlineResponse20032 {
  /**
   * Exchange parameter id
   * @type {string}
   * @memberof InlineResponse20032
   */
  id?: string;
  /**
   * Reference on a trade venue of given exchange parameter
   * @type {string}
   * @memberof InlineResponse20032
   */
  tradeVenueId?: string;
  /**
   * Always contains at least one 'tradingTime'  and zero or more 'sessionTime' tags
   * @type {Array<InlineResponse20032Schedules>}
   * @memberof InlineResponse20032
   */
  schedules?: Array<InlineResponse20032Schedules>;
}

export function InlineResponse20032FromJSON(json: any): InlineResponse20032 {
  return InlineResponse20032FromJSONTyped(json, false);
}

export function InlineResponse20032FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20032 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    tradeVenueId: !exists(json, "tradeVenueId")
      ? undefined
      : json["tradeVenueId"],
    schedules: !exists(json, "schedules")
      ? undefined
      : (json["schedules"] as Array<any>).map(
          InlineResponse20032SchedulesFromJSON
        ),
  };
}

export function InlineResponse20032ToJSON(
  value?: InlineResponse20032 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    tradeVenueId: value.tradeVenueId,
    schedules:
      value.schedules === undefined
        ? undefined
        : (value.schedules as Array<any>).map(
            InlineResponse20032SchedulesToJSON
          ),
  };
}
