// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  InlineResponse2006E,
  InlineResponse2006EFromJSON,
  InlineResponse2006EFromJSONTyped,
  InlineResponse2006EToJSON,
} from './'

/**
 *
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
  /**
   * Email option is enabled or not 0-off, 1-on.
   * @type {number}
   * @memberof InlineResponse2006
   */
  m?: number
  /**
   *
   * @type {Array<InlineResponse2006E>}
   * @memberof InlineResponse2006
   */
  e?: Array<InlineResponse2006E>
}

export function InlineResponse2006FromJSON(json: any): InlineResponse2006 {
  return InlineResponse2006FromJSONTyped(json, false)
}

export function InlineResponse2006FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2006 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    m: !exists(json, 'M') ? undefined : json['M'],
    e: !exists(json, 'E')
      ? undefined
      : (json['E'] as Array<any>).map(InlineResponse2006EFromJSON),
  }
}

export function InlineResponse2006ToJSON(
  value?: InlineResponse2006 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    M: value.m,
    E:
      value.e === undefined
        ? undefined
        : (value.e as Array<any>).map(InlineResponse2006EToJSON),
  }
}
