// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  InlineResponse20029FilterList,
  InlineResponse20029FilterListFromJSON,
  InlineResponse20029FilterListFromJSONTyped,
  InlineResponse20029FilterListToJSON,
  InlineResponse20029InstrumentList,
  InlineResponse20029InstrumentListFromJSON,
  InlineResponse20029InstrumentListFromJSONTyped,
  InlineResponse20029InstrumentListToJSON,
  InlineResponse20029LocationTree,
  InlineResponse20029LocationTreeFromJSON,
  InlineResponse20029LocationTreeFromJSONTyped,
  InlineResponse20029LocationTreeToJSON,
  InlineResponse20029ScanTypeList,
  InlineResponse20029ScanTypeListFromJSON,
  InlineResponse20029ScanTypeListFromJSONTyped,
  InlineResponse20029ScanTypeListToJSON,
} from "./";

/**
 *
 * @export
 * @interface InlineResponse20029
 */
export interface InlineResponse20029 {
  /**
   *
   * @type {Array<InlineResponse20029ScanTypeList>}
   * @memberof InlineResponse20029
   */
  scanTypeList?: Array<InlineResponse20029ScanTypeList>;
  /**
   *
   * @type {Array<InlineResponse20029InstrumentList>}
   * @memberof InlineResponse20029
   */
  instrumentList?: Array<InlineResponse20029InstrumentList>;
  /**
   *
   * @type {Array<InlineResponse20029FilterList>}
   * @memberof InlineResponse20029
   */
  filterList?: Array<InlineResponse20029FilterList>;
  /**
   *
   * @type {Array<InlineResponse20029LocationTree>}
   * @memberof InlineResponse20029
   */
  locationTree?: Array<InlineResponse20029LocationTree>;
}

export function InlineResponse20029FromJSON(json: any): InlineResponse20029 {
  return InlineResponse20029FromJSONTyped(json, false);
}

export function InlineResponse20029FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20029 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    scanTypeList: !exists(json, "scan_type_list")
      ? undefined
      : (json["scan_type_list"] as Array<any>).map(
          InlineResponse20029ScanTypeListFromJSON
        ),
    instrumentList: !exists(json, "instrument_list")
      ? undefined
      : (json["instrument_list"] as Array<any>).map(
          InlineResponse20029InstrumentListFromJSON
        ),
    filterList: !exists(json, "filter_list")
      ? undefined
      : (json["filter_list"] as Array<any>).map(
          InlineResponse20029FilterListFromJSON
        ),
    locationTree: !exists(json, "location_tree")
      ? undefined
      : (json["location_tree"] as Array<any>).map(
          InlineResponse20029LocationTreeFromJSON
        ),
  };
}

export function InlineResponse20029ToJSON(
  value?: InlineResponse20029 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    scan_type_list:
      value.scanTypeList === undefined
        ? undefined
        : (value.scanTypeList as Array<any>).map(
            InlineResponse20029ScanTypeListToJSON
          ),
    instrument_list:
      value.instrumentList === undefined
        ? undefined
        : (value.instrumentList as Array<any>).map(
            InlineResponse20029InstrumentListToJSON
          ),
    filter_list:
      value.filterList === undefined
        ? undefined
        : (value.filterList as Array<any>).map(
            InlineResponse20029FilterListToJSON
          ),
    location_tree:
      value.locationTree === undefined
        ? undefined
        : (value.locationTree as Array<any>).map(
            InlineResponse20029LocationTreeToJSON
          ),
  };
}
