// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineObject13
 */
export interface InlineObject13 {
  /**
   *
   * @type {Array<string>}
   * @memberof InlineObject13
   */
  acctIds?: Array<string>;
  /**
   *
   * @type {Array<number>}
   * @memberof InlineObject13
   */
  conids?: Array<number>;
  /**
   * optional defaults to USD.
   * @type {string}
   * @memberof InlineObject13
   */
  currency?: string;
  /**
   * optional, default value is 90
   * @type {number}
   * @memberof InlineObject13
   */
  days?: number;
}

export function InlineObject13FromJSON(json: any): InlineObject13 {
  return InlineObject13FromJSONTyped(json, false);
}

export function InlineObject13FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject13 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    acctIds: !exists(json, "acctIds") ? undefined : json["acctIds"],
    conids: !exists(json, "conids") ? undefined : json["conids"],
    currency: !exists(json, "currency") ? undefined : json["currency"],
    days: !exists(json, "days") ? undefined : json["days"],
  };
}

export function InlineObject13ToJSON(value?: InlineObject13 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    acctIds: value.acctIds,
    conids: value.conids,
    currency: value.currency,
    days: value.days,
  };
}
