// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineResponse20028OrderTypesOutside
 */
export interface InlineResponse20028OrderTypesOutside {
  /**
   * order types that support outside of regular trading hours
   * @type {string}
   * @memberof InlineResponse20028OrderTypesOutside
   */
  _0?: string
}

export function InlineResponse20028OrderTypesOutsideFromJSON(
  json: any
): InlineResponse20028OrderTypesOutside {
  return InlineResponse20028OrderTypesOutsideFromJSONTyped(json, false)
}

export function InlineResponse20028OrderTypesOutsideFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20028OrderTypesOutside {
  if (json === undefined || json === null) {
    return json
  }
  return {
    _0: !exists(json, '0') ? undefined : json['0'],
  }
}

export function InlineResponse20028OrderTypesOutsideToJSON(
  value?: InlineResponse20028OrderTypesOutside | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    '0': value._0,
  }
}
