// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  IserverContractConidAlgosParameters,
  IserverContractConidAlgosParametersFromJSON,
  IserverContractConidAlgosParametersFromJSONTyped,
  IserverContractConidAlgosParametersToJSON,
} from "./";

/**
 *
 * @export
 * @interface InlineResponse20027
 */
export interface InlineResponse20027 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20027
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20027
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20027
   */
  id?: string;
  /**
   *
   * @type {Array<IserverContractConidAlgosParameters>}
   * @memberof InlineResponse20027
   */
  parameters?: Array<IserverContractConidAlgosParameters>;
}

export function InlineResponse20027FromJSON(json: any): InlineResponse20027 {
  return InlineResponse20027FromJSONTyped(json, false);
}

export function InlineResponse20027FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20027 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    id: !exists(json, "id") ? undefined : json["id"],
    parameters: !exists(json, "parameters")
      ? undefined
      : (json["parameters"] as Array<any>).map(
          IserverContractConidAlgosParametersFromJSON
        ),
  };
}

export function InlineResponse20027ToJSON(
  value?: InlineResponse20027 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    id: value.id,
    parameters:
      value.parameters === undefined
        ? undefined
        : (value.parameters as Array<any>).map(
            IserverContractConidAlgosParametersToJSON
          ),
  };
}
