// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20021
 */
export interface InlineResponse20021 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20021
   */
  orderId?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20021
   */
  msg?: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20021
   */
  conid?: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20021
   */
  account?: string;
}

export function InlineResponse20021FromJSON(json: any): InlineResponse20021 {
  return InlineResponse20021FromJSONTyped(json, false);
}

export function InlineResponse20021FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20021 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderId: !exists(json, "order_id") ? undefined : json["order_id"],
    msg: !exists(json, "msg") ? undefined : json["msg"],
    conid: !exists(json, "conid") ? undefined : json["conid"],
    account: !exists(json, "account") ? undefined : json["account"],
  };
}

export function InlineResponse20021ToJSON(
  value?: InlineResponse20021 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    order_id: value.orderId,
    msg: value.msg,
    conid: value.conid,
    account: value.account,
  };
}
