/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
  /**
   * alert id(order id)
   * @type {number}
   * @memberof InlineObject3
   */
  alertId?: number;
  /**
   * 1 to activate, 0 to deactivate
   * @type {number}
   * @memberof InlineObject3
   */
  alertActive?: number;
}

export function InlineObject3FromJSON(json: any): InlineObject3 {
  return InlineObject3FromJSONTyped(json, false);
}

export function InlineObject3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject3 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    alertId: !exists(json, "alertId") ? undefined : json["alertId"],
    alertActive: !exists(json, "alertActive") ? undefined : json["alertActive"],
  };
}

export function InlineObject3ToJSON(value?: InlineObject3 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    alertId: value.alertId,
    alertActive: value.alertActive,
  };
}
