// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
  /**
   *
   * @type {Array<string>}
   * @memberof InlineObject4
   */
  filters?: Array<InlineObject4FiltersEnum>
}

/**
 * @export
 * @enum {string}
 */
export enum InlineObject4FiltersEnum {
  Inactive = 'inactive',
  PendingSubmit = 'pending_submit',
  PreSubmitted = 'pre_submitted',
  Submitted = 'submitted',
  Filled = 'filled',
  PendingCancel = 'pending_cancel',
  Cancelled = 'cancelled',
  WarnState = 'warn_state',
  SortByTime = 'sort_by_time',
}

export function InlineObject4FromJSON(json: any): InlineObject4 {
  return InlineObject4FromJSONTyped(json, false)
}

export function InlineObject4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject4 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    filters: !exists(json, 'filters') ? undefined : json['filters'],
  }
}

export function InlineObject4ToJSON(value?: InlineObject4 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    filters: value.filters,
  }
}
