/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20024
 */
export interface InlineResponse20024 {
  /**
   * true means market data is cancelled, false means it is not.
   * @type {boolean}
   * @memberof InlineResponse20024
   */
  confirmed?: boolean;
}

export function InlineResponse20024FromJSON(json: any): InlineResponse20024 {
  return InlineResponse20024FromJSONTyped(json, false);
}

export function InlineResponse20024FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20024 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    confirmed: !exists(json, "confirmed") ? undefined : json["confirmed"],
  };
}

export function InlineResponse20024ToJSON(
  value?: InlineResponse20024 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    confirmed: value.confirmed,
  };
}
