/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse4001
 */
export interface InlineResponse4001 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse4001
   */
  error?: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse4001
   */
  statusCode?: number;
}

export function InlineResponse4001FromJSON(json: any): InlineResponse4001 {
  return InlineResponse4001FromJSONTyped(json, false);
}

export function InlineResponse4001FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse4001 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    error: !exists(json, "error") ? undefined : json["error"],
    statusCode: !exists(json, "statusCode") ? undefined : json["statusCode"],
  };
}

export function InlineResponse4001ToJSON(
  value?: InlineResponse4001 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    error: value.error,
    statusCode: value.statusCode,
  };
}
