// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20019Amount
 */
export interface InlineResponse20019Amount {
  /**
   * for example 23,000 USD
   * @type {string}
   * @memberof InlineResponse20019Amount
   */
  amount?: string;
  /**
   * for example 1.1 ... 1.2 USD
   * @type {string}
   * @memberof InlineResponse20019Amount
   */
  commission?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20019Amount
   */
  total?: string;
}

export function InlineResponse20019AmountFromJSON(
  json: any
): InlineResponse20019Amount {
  return InlineResponse20019AmountFromJSONTyped(json, false);
}

export function InlineResponse20019AmountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20019Amount {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    amount: !exists(json, "amount") ? undefined : json["amount"],
    commission: !exists(json, "commission") ? undefined : json["commission"],
    total: !exists(json, "total") ? undefined : json["total"],
  };
}

export function InlineResponse20019AmountToJSON(
  value?: InlineResponse20019Amount | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    amount: value.amount,
    commission: value.commission,
    total: value.total,
  };
}
