/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  IbcustEntityInfoEntities,
  IbcustEntityInfoEntitiesFromJSON,
  IbcustEntityInfoEntitiesFromJSONTyped,
  IbcustEntityInfoEntitiesToJSON,
} from "./";

/**
 *
 * @export
 * @interface InlineResponse20039
 */
export interface InlineResponse20039 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse20039
   */
  applicantId?: number;
  /**
   *
   * @type {Array<IbcustEntityInfoEntities>}
   * @memberof InlineResponse20039
   */
  entities?: Array<IbcustEntityInfoEntities>;
}

export function InlineResponse20039FromJSON(json: any): InlineResponse20039 {
  return InlineResponse20039FromJSONTyped(json, false);
}

export function InlineResponse20039FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20039 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    applicantId: !exists(json, "applicantId") ? undefined : json["applicantId"],
    entities: !exists(json, "entities")
      ? undefined
      : (json["entities"] as Array<any>).map(IbcustEntityInfoEntitiesFromJSON),
  };
}

export function InlineResponse20039ToJSON(
  value?: InlineResponse20039 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    applicantId: value.applicantId,
    entities:
      value.entities === undefined
        ? undefined
        : (value.entities as Array<any>).map(IbcustEntityInfoEntitiesToJSON),
  };
}
