/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20012
 */
export interface InlineResponse20012 {
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse20012
   */
  set?: boolean;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20012
   */
  acctId?: string;
}

export function InlineResponse20012FromJSON(json: any): InlineResponse20012 {
  return InlineResponse20012FromJSONTyped(json, false);
}

export function InlineResponse20012FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20012 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: !exists(json, "set") ? undefined : json["set"],
    acctId: !exists(json, "acctId") ? undefined : json["acctId"],
  };
}

export function InlineResponse20012ToJSON(
  value?: InlineResponse20012 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    acctId: value.acctId,
  };
}
