// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
  /**
   * answer to question, true means yes, false means no
   * @type {boolean}
   * @memberof InlineObject6
   */
  confirmed?: boolean;
}

export function InlineObject6FromJSON(json: any): InlineObject6 {
  return InlineObject6FromJSONTyped(json, false);
}

export function InlineObject6FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject6 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    confirmed: !exists(json, "confirmed") ? undefined : json["confirmed"],
  };
}

export function InlineObject6ToJSON(value?: InlineObject6 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    confirmed: value.confirmed,
  };
}
