/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * device
 * @export
 * @interface InlineResponse2006E
 */
export interface InlineResponse2006E {
  /**
   * device name
   * @type {string}
   * @memberof InlineResponse2006E
   */
  nM?: string;
  /**
   * device id
   * @type {string}
   * @memberof InlineResponse2006E
   */
  i?: string;
  /**
   * unique device id
   * @type {string}
   * @memberof InlineResponse2006E
   */
  uI?: string;
  /**
   * device is enabled or not 0-true, 1-false.
   * @type {string}
   * @memberof InlineResponse2006E
   */
  a?: string;
}

export function InlineResponse2006EFromJSON(json: any): InlineResponse2006E {
  return InlineResponse2006EFromJSONTyped(json, false);
}

export function InlineResponse2006EFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2006E {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    nM: !exists(json, "NM") ? undefined : json["NM"],
    i: !exists(json, "I") ? undefined : json["I"],
    uI: !exists(json, "UI") ? undefined : json["UI"],
    a: !exists(json, "A") ? undefined : json["A"],
  };
}

export function InlineResponse2006EToJSON(
  value?: InlineResponse2006E | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    NM: value.nM,
    I: value.i,
    UI: value.uI,
    A: value.a,
  };
}
