// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
  /**
   * Challenge in hex format
   * @type {object}
   * @memberof InlineResponse2001
   */
  challenge?: object
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
  return InlineResponse2001FromJSONTyped(json, false)
}

export function InlineResponse2001FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    challenge: !exists(json, 'challenge') ? undefined : json['challenge'],
  }
}

export function InlineResponse2001ToJSON(
  value?: InlineResponse2001 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    challenge: value.challenge,
  }
}
