// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  requestId?: number
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  orderId?: number
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse20013
   */
  success?: boolean
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  text?: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  orderStatus?: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  warningMessage?: string
}

export function InlineResponse20013FromJSON(json: any): InlineResponse20013 {
  return InlineResponse20013FromJSONTyped(json, false)
}

export function InlineResponse20013FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20013 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    requestId: !exists(json, 'request_id') ? undefined : json['request_id'],
    orderId: !exists(json, 'order_id') ? undefined : json['order_id'],
    success: !exists(json, 'success') ? undefined : json['success'],
    text: !exists(json, 'text') ? undefined : json['text'],
    orderStatus: !exists(json, 'order_status')
      ? undefined
      : json['order_status'],
    warningMessage: !exists(json, 'warning_message')
      ? undefined
      : json['warning_message'],
  }
}

export function InlineResponse20013ToJSON(
  value?: InlineResponse20013 | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    request_id: value.requestId,
    order_id: value.orderId,
    success: value.success,
    text: value.text,
    order_status: value.orderStatus,
    warning_message: value.warningMessage,
  }
}
