// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
  /**
   * disclaimer message
   * @type {string}
   * @memberof InlineResponse2004
   */
  dT?: string;
  /**
   * fyi code
   * @type {string}
   * @memberof InlineResponse2004
   */
  fC?: string;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
  return InlineResponse2004FromJSONTyped(json, false);
}

export function InlineResponse2004FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2004 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dT: !exists(json, "DT") ? undefined : json["DT"],
    fC: !exists(json, "FC") ? undefined : json["FC"],
  };
}

export function InlineResponse2004ToJSON(
  value?: InlineResponse2004 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    DT: value.dT,
    FC: value.fC,
  };
}
