/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse2009AcctList
 */
export interface InlineResponse2009AcctList {
  /**
   * For multi-account structures each trading account will numbered from 0 to ...
   * @type {string}
   * @memberof InlineResponse2009AcctList
   */
  _0?: string;
}

export function InlineResponse2009AcctListFromJSON(
  json: any
): InlineResponse2009AcctList {
  return InlineResponse2009AcctListFromJSONTyped(json, false);
}

export function InlineResponse2009AcctListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2009AcctList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    _0: !exists(json, "0") ? undefined : json["0"],
  };
}

export function InlineResponse2009AcctListToJSON(
  value?: InlineResponse2009AcctList | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    "0": value._0,
  };
}
