// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InlineResponse20029FilterList
 */
export interface InlineResponse20029FilterList {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20029FilterList
   */
  group?: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20029FilterList
   */
  displayName?: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20029FilterList
   */
  code?: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20029FilterList
   */
  type?: string
}

export function InlineResponse20029FilterListFromJSON(
  json: any
): InlineResponse20029FilterList {
  return InlineResponse20029FilterListFromJSONTyped(json, false)
}

export function InlineResponse20029FilterListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20029FilterList {
  if (json === undefined || json === null) {
    return json
  }
  return {
    group: !exists(json, 'group') ? undefined : json['group'],
    displayName: !exists(json, 'display_name')
      ? undefined
      : json['display_name'],
    code: !exists(json, 'code') ? undefined : json['code'],
    type: !exists(json, 'type') ? undefined : json['type'],
  }
}

export function InlineResponse20029FilterListToJSON(
  value?: InlineResponse20029FilterList | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    group: value.group,
    display_name: value.displayName,
    code: value.code,
    type: value.type,
  }
}
