/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20018
 */
export interface InlineResponse20018 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20018
   */
  orderId?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20018
   */
  orderStatus?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20018
   */
  localOrderId?: string;
}

export function InlineResponse20018FromJSON(json: any): InlineResponse20018 {
  return InlineResponse20018FromJSONTyped(json, false);
}

export function InlineResponse20018FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20018 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderId: !exists(json, "order_id") ? undefined : json["order_id"],
    orderStatus: !exists(json, "order_status")
      ? undefined
      : json["order_status"],
    localOrderId: !exists(json, "local_order_id")
      ? undefined
      : json["local_order_id"],
  };
}

export function InlineResponse20018ToJSON(
  value?: InlineResponse20018 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    order_id: value.orderId,
    order_status: value.orderStatus,
    local_order_id: value.localOrderId,
  };
}
