// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20038
 */
export interface InlineResponse20038 {
  /**
   * 1 for Live, 2 for Paper
   * @type {number}
   * @memberof InlineResponse20038
   */
  lOGINTYPE?: number;
  /**
   * Username
   * @type {string}
   * @memberof InlineResponse20038
   */
  uSERNAME?: string;
  /**
   * User ID
   * @type {number}
   * @memberof InlineResponse20038
   */
  uSERID?: number;
  /**
   * Time in milliseconds until session expires. Caller needs to call the again to re-validate session
   * @type {number}
   * @memberof InlineResponse20038
   */
  expire?: number;
  /**
   * true if session was validated; false if not.
   * @type {boolean}
   * @memberof InlineResponse20038
   */
  rESULT?: boolean;
  /**
   * Time of session validation
   * @type {number}
   * @memberof InlineResponse20038
   */
  aUTHTIME?: number;
}

export function InlineResponse20038FromJSON(json: any): InlineResponse20038 {
  return InlineResponse20038FromJSONTyped(json, false);
}

export function InlineResponse20038FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20038 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lOGINTYPE: !exists(json, "LOGIN_TYPE") ? undefined : json["LOGIN_TYPE"],
    uSERNAME: !exists(json, "USER_NAME") ? undefined : json["USER_NAME"],
    uSERID: !exists(json, "USER_ID") ? undefined : json["USER_ID"],
    expire: !exists(json, "expire") ? undefined : json["expire"],
    rESULT: !exists(json, "RESULT") ? undefined : json["RESULT"],
    aUTHTIME: !exists(json, "AUTH_TIME") ? undefined : json["AUTH_TIME"],
  };
}

export function InlineResponse20038ToJSON(
  value?: InlineResponse20038 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    LOGIN_TYPE: value.lOGINTYPE,
    USER_NAME: value.uSERNAME,
    USER_ID: value.uSERID,
    expire: value.expire,
    RESULT: value.rESULT,
    AUTH_TIME: value.aUTHTIME,
  };
}
