// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20017
 */
export interface InlineResponse20017 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20017
   */
  id?: string;
  /**
   * Please note here, if the message is a question, you have to reply to question in order to submit
   * the order successfully. See more in the "/iserver/reply/{replyid}" endpoint.
   * @type {Array<string>}
   * @memberof InlineResponse20017
   */
  message?: Array<string>;
}

export function InlineResponse20017FromJSON(json: any): InlineResponse20017 {
  return InlineResponse20017FromJSONTyped(json, false);
}

export function InlineResponse20017FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20017 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    message: !exists(json, "message") ? undefined : json["message"],
  };
}

export function InlineResponse20017ToJSON(
  value?: InlineResponse20017 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    message: value.message,
  };
}
