/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 {
  /**
   * Login session is authenticated to the CCP.
   * @type {boolean}
   * @memberof InlineResponse2008
   */
  authenticated?: boolean;
  /**
   * Login session is connected
   * @type {boolean}
   * @memberof InlineResponse2008
   */
  connected?: boolean;
  /**
   * server name
   * @type {string}
   * @memberof InlineResponse2008
   */
  name?: string;
}

export function InlineResponse2008FromJSON(json: any): InlineResponse2008 {
  return InlineResponse2008FromJSONTyped(json, false);
}

export function InlineResponse2008FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2008 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    authenticated: !exists(json, "authenticated")
      ? undefined
      : json["authenticated"],
    connected: !exists(json, "connected") ? undefined : json["connected"],
    name: !exists(json, "name") ? undefined : json["name"],
  };
}

export function InlineResponse2008ToJSON(
  value?: InlineResponse2008 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    authenticated: value.authenticated,
    connected: value.connected,
    name: value.name,
  };
}
