// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InlineResponse20023
 */
export interface InlineResponse20023 {
  /**
   * success means market data was cancelled.
   * @type {string}
   * @memberof InlineResponse20023
   */
  confirmed?: string;
}

export function InlineResponse20023FromJSON(json: any): InlineResponse20023 {
  return InlineResponse20023FromJSONTyped(json, false);
}

export function InlineResponse20023FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse20023 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    confirmed: !exists(json, "confirmed") ? undefined : json["confirmed"],
  };
}

export function InlineResponse20023ToJSON(
  value?: InlineResponse20023 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    confirmed: value.confirmed,
  };
}
