// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  PerformanceCpsData,
  PerformanceCpsDataFromJSON,
  PerformanceCpsDataFromJSONTyped,
  PerformanceCpsDataToJSON,
} from './'

/**
 * Net asset value data for the account or consolidated accounts. NAV data is not applicable to benchmarks.
 * @export
 * @interface PerformanceNav
 */
export interface PerformanceNav {
  /**
   * array of dates, the length should be same as the length of returns inside data.
   * @type {Array<string>}
   * @memberof PerformanceNav
   */
  dates?: Array<string>
  /**
   * D means Day
   * @type {string}
   * @memberof PerformanceNav
   */
  freq?: string
  /**
   *
   * @type {Array<PerformanceCpsData>}
   * @memberof PerformanceNav
   */
  data?: Array<PerformanceCpsData>
}

export function PerformanceNavFromJSON(json: any): PerformanceNav {
  return PerformanceNavFromJSONTyped(json, false)
}

export function PerformanceNavFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PerformanceNav {
  if (json === undefined || json === null) {
    return json
  }
  return {
    dates: !exists(json, 'dates') ? undefined : json['dates'],
    freq: !exists(json, 'freq') ? undefined : json['freq'],
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(PerformanceCpsDataFromJSON),
  }
}

export function PerformanceNavToJSON(value?: PerformanceNav | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    dates: value.dates,
    freq: value.freq,
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(PerformanceCpsDataToJSON),
  }
}
