/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PositionData
 */
export interface PositionData {
  /**
   * Contract identifier from IBKR's database.
   * @type {number}
   * @memberof PositionData
   */
  conid?: number;
  /**
   * Number of shares or quantity of the position.
   * @type {number}
   * @memberof PositionData
   */
  position?: number;
  /**
   * Average cost of the position.
   * @type {number}
   * @memberof PositionData
   */
  avgCost?: number;
}

export function PositionDataFromJSON(json: any): PositionData {
  return PositionDataFromJSONTyped(json, false);
}

export function PositionDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PositionData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    conid: !exists(json, "conid") ? undefined : json["conid"],
    position: !exists(json, "position") ? undefined : json["position"],
    avgCost: !exists(json, "avgCost") ? undefined : json["avgCost"],
  };
}

export function PositionDataToJSON(value?: PositionData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    conid: value.conid,
    position: value.position,
    avgCost: value.avgCost,
  };
}
