/* tslint:disable */
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  ScannerResultContractsContract,
  ScannerResultContractsContractFromJSON,
  ScannerResultContractsContractFromJSONTyped,
  ScannerResultContractsContractToJSON,
} from "./";

/**
 * Contains list of contracts matching the scanner query
 * @export
 * @interface ScannerResultContracts
 */
export interface ScannerResultContracts {
  /**
   *
   * @type {Array<ScannerResultContractsContract>}
   * @memberof ScannerResultContracts
   */
  contract?: Array<ScannerResultContractsContract>;
}

export function ScannerResultContractsFromJSON(
  json: any
): ScannerResultContracts {
  return ScannerResultContractsFromJSONTyped(json, false);
}

export function ScannerResultContractsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScannerResultContracts {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    contract: !exists(json, "Contract")
      ? undefined
      : (json["Contract"] as Array<any>).map(
          ScannerResultContractsContractFromJSON
        ),
  };
}

export function ScannerResultContractsToJSON(
  value?: ScannerResultContracts | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Contract:
      value.contract === undefined
        ? undefined
        : (value.contract as Array<any>).map(
            ScannerResultContractsContractToJSON
          ),
  };
}
