// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  ScannerParamsInstrumentListInstrument,
  ScannerParamsInstrumentListInstrumentFromJSON,
  ScannerParamsInstrumentListInstrumentFromJSONTyped,
  ScannerParamsInstrumentListInstrumentToJSON,
} from "./";

/**
 * Contains list of instruments for which scanner can be ran
 * @export
 * @interface ScannerParamsInstrumentList
 */
export interface ScannerParamsInstrumentList {
  /**
   * Contains information like name, supported filters, etc. for an instrument
   * @type {Array<ScannerParamsInstrumentListInstrument>}
   * @memberof ScannerParamsInstrumentList
   */
  instrument?: Array<ScannerParamsInstrumentListInstrument>;
}

export function ScannerParamsInstrumentListFromJSON(
  json: any
): ScannerParamsInstrumentList {
  return ScannerParamsInstrumentListFromJSONTyped(json, false);
}

export function ScannerParamsInstrumentListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScannerParamsInstrumentList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    instrument: !exists(json, "Instrument")
      ? undefined
      : (json["Instrument"] as Array<any>).map(
          ScannerParamsInstrumentListInstrumentFromJSON
        ),
  };
}

export function ScannerParamsInstrumentListToJSON(
  value?: ScannerParamsInstrumentList | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Instrument:
      value.instrument === undefined
        ? undefined
        : (value.instrument as Array<any>).map(
            ScannerParamsInstrumentListInstrumentToJSON
          ),
  };
}
