// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SummaryTotal
 */
export interface SummaryTotal {
  /**
   * total change amount
   * @type {string}
   * @memberof SummaryTotal
   */
  chg?: string
  /**
   * change percent
   * @type {string}
   * @memberof SummaryTotal
   */
  rtn?: string
  /**
   * set to true if any external account data is not available for starting or ending date, resulting in potentially unusual total values.
   * @type {boolean}
   * @memberof SummaryTotal
   */
  incompleteData?: boolean
  /**
   *
   * @type {string}
   * @memberof SummaryTotal
   */
  endVal?: string
  /**
   *
   * @type {string}
   * @memberof SummaryTotal
   */
  startVal?: string
}

export function SummaryTotalFromJSON(json: any): SummaryTotal {
  return SummaryTotalFromJSONTyped(json, false)
}

export function SummaryTotalFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SummaryTotal {
  if (json === undefined || json === null) {
    return json
  }
  return {
    chg: !exists(json, 'chg') ? undefined : json['chg'],
    rtn: !exists(json, 'rtn') ? undefined : json['rtn'],
    incompleteData: !exists(json, 'incompleteData')
      ? undefined
      : json['incompleteData'],
    endVal: !exists(json, 'endVal') ? undefined : json['endVal'],
    startVal: !exists(json, 'startVal') ? undefined : json['startVal'],
  }
}

export function SummaryTotalToJSON(value?: SummaryTotal | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    chg: value.chg,
    rtn: value.rtn,
    incompleteData: value.incompleteData,
    endVal: value.endVal,
    startVal: value.startVal,
  }
}
