// @ts-nocheck
/* eslint-disable */
/**
 * Client Portal Web API
 * Client Poral Web API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SummaryAccountSummaries
 */
export interface SummaryAccountSummaries {
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  chg?: string
  /**
   *
   * @type {boolean}
   * @memberof SummaryAccountSummaries
   */
  hasAccounts?: boolean
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  accountTypeName?: string
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  rtn?: string
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  endVal?: string
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  accountTypeCode?: string
  /**
   *
   * @type {string}
   * @memberof SummaryAccountSummaries
   */
  startVal?: string
}

export function SummaryAccountSummariesFromJSON(
  json: any
): SummaryAccountSummaries {
  return SummaryAccountSummariesFromJSONTyped(json, false)
}

export function SummaryAccountSummariesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SummaryAccountSummaries {
  if (json === undefined || json === null) {
    return json
  }
  return {
    chg: !exists(json, 'chg') ? undefined : json['chg'],
    hasAccounts: !exists(json, 'hasAccounts') ? undefined : json['hasAccounts'],
    accountTypeName: !exists(json, 'accountTypeName')
      ? undefined
      : json['accountTypeName'],
    rtn: !exists(json, 'rtn') ? undefined : json['rtn'],
    endVal: !exists(json, 'endVal') ? undefined : json['endVal'],
    accountTypeCode: !exists(json, 'accountTypeCode')
      ? undefined
      : json['accountTypeCode'],
    startVal: !exists(json, 'startVal') ? undefined : json['startVal'],
  }
}

export function SummaryAccountSummariesToJSON(
  value?: SummaryAccountSummaries | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    chg: value.chg,
    hasAccounts: value.hasAccounts,
    accountTypeName: value.accountTypeName,
    rtn: value.rtn,
    endVal: value.endVal,
    accountTypeCode: value.accountTypeCode,
    startVal: value.startVal,
  }
}
